# Generated by Django 6.0.2 on 2026-09-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempedido', '0003_alter_itempedido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
