# Generated by Django 5.2.17 on 2026-09-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('GARÇOM', 'Garçom'), ('COZINHEIRO', 'Cozinheiro')], max_length=20),
        ),
    ]
